website is now linked to readme
sachin235/30Days-of-GCP pull request #60
Opened 2021-10-25 19:58 UTC by Sajal193

The link which wasn't working on the readme file is now active. It is now redirecting the user to the GCP main page.

2021-10-25 20:53 UTC, sachin235 requested changes

2021-10-25 20:53 UTC, sachin235 commented on README.md
> +
Remove it from here

2021-10-25 20:53 UTC, sachin235 commented on README.md
>  Along the way, you will learn & practice concepts like computing, application development, big data & machine learning using cloud & if you get stuck, you will have your "Campus Facilitators" who are
Remove this as well. Its not required.

2021-10-25 20:53 UTC, sachin235 commented on README.md
>  The program will introduce you to Computing, Application Development, Big Data & Machine Learning using Google Cloud's training platform called Google Cloud Skills Boost where you will learn each of
Make it
The [30 Days of GCP](link the program website here) program ....

2021-10-25 20:53 UTC, sachin235 commented on README.md
Remove this as all this is available on the program website.

2021-10-25 20:53 UTC, sachin235 commented on README.md
> +<li>CLOUD ENGINEERING Track
Capitalise TRACK as well to make it synchronous

2021-10-25 20:53 UTC, sachin235 commented on README.md
> +
Capitalise TRACK as well to make it synchronous

2021-10-26 06:14 UTC, Sajal193 commented
Dear sir, I have made the changes required. Please review them and advise if any further changes are required.

2021-10-26 07:01 UTC, sachin235 commented
Looks good to me.

2021-10-26 07:01 UTC, merged